/**
 * Customer profile handlers — manage display name, phone, and avatar.
 *
 * Each exported function takes a `CustomerContext` (built by
 * `customerRoute`) and returns a `NextResponse`. The route files in
 * `app/api/customer/profile/` and `app/api/customer/avatar/` wire
 * these handlers through the customer middleware pipeline.
 *
 * Field mutability rules:
 *
 *   - `email`          — always locked (change requires separate flow)
 *   - `displayName`    — always editable
 *   - `phone`          — editable until kycFieldsLocked becomes true
 *   - `fullName`       — immutable (set by Didit, never editable)
 *   - `dateOfBirth`    — immutable
 *   - `nationality`    — immutable
 *   - `documentType`   — immutable
 *   - `documentCountry`— immutable
 *   - `addressLine`    — immutable
 *   - `addressCity`    — immutable
 *   - `addressCountry` — immutable
 *
 * @module
 */

import { NextResponse } from 'next/server';
import { and, eq, isNull, ne } from 'drizzle-orm';
import { z } from 'zod';
import { displayNameSchema, phoneSchema } from '@/lib/validation/profile';

import type { CustomerContext } from '../context';
import * as schema from '@/lib/db/schema';
import { SHARP_INPUT_GUARD } from '@/lib/image/sharp-limits';
import { writeAudit } from '@/lib/audit/writer';
import { customerActor, customerLabel } from '@/lib/audit/actors';
import { uuidTarget } from '@/lib/audit/targets';
import { buildRequestContext as buildAuditRequestContext } from '@/lib/audit/context';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Maximum avatar file size in bytes: 2 MiB. */
const MAX_AVATAR_BYTES = 2 * 1024 * 1024;

/** JPEG magic bytes (first 3 bytes). */
const JPEG_MAGIC = new Uint8Array([0xff, 0xd8, 0xff]);

/** PNG magic bytes (first 4 bytes). */
const PNG_MAGIC = new Uint8Array([0x89, 0x50, 0x4e, 0x47]);

/** WebP: starts with "RIFF" (4 bytes), then 4 bytes size, then "WEBP" (4 bytes). */
const RIFF_MAGIC = new Uint8Array([0x52, 0x49, 0x46, 0x46]);
const WEBP_MAGIC = new Uint8Array([0x57, 0x45, 0x42, 0x50]);

// ---------------------------------------------------------------------------
// Validation schema
// ---------------------------------------------------------------------------

const UpdateProfileSchema = z
  .object({
    displayName: displayNameSchema.optional(),
    phone: phoneSchema.optional(),
    onboardingDismissed: z.literal(true).optional(),
  })
  .strict();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Normalize a display name: NFC normalize, strip HTML tags, strip control
 * characters (except space/newline/tab which are also stripped for display
 * names).
 */
function normalizeDisplayName(raw: string): string {
  // NFC normalize Unicode
  let result = raw.normalize('NFC');
  // Strip HTML tags
  result = result.replace(/<[^>]*>/g, '');
  // Strip control characters (U+0000..U+001F, U+007F..U+009F)
  result = result.replace(/[\u0000-\u001f\u007f-\u009f]/g, '');
  // Collapse whitespace and trim
  result = result.replace(/\s+/g, ' ').trim();
  return result;
}

/**
 * Build the mutability map for profile fields based on the current
 * kycFieldsLocked state.
 */
function buildMutabilityMap(kycFieldsLocked: boolean): Record<string, string> {
  return {
    email: 'locked',
    displayName: 'editable',
    phone: kycFieldsLocked ? 'locked' : 'editable',
    fullName: 'immutable',
    dateOfBirth: 'immutable',
    nationality: 'immutable',
    documentType: 'immutable',
    documentCountry: 'immutable',
    addressLine: 'immutable',
    addressCity: 'immutable',
    addressCountry: 'immutable',
  };
}

/**
 * Get the base path for avatar file storage. Uses process.cwd() + /data/uploads/avatars/.
 */
function getAvatarBasePath(): string {
  return `${process.cwd()}/data/uploads/avatars`;
}

/** UUID format regex (non-v4-specific; storage keys are generated by crypto.randomUUID). */
const AVATAR_STORAGE_KEY_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Read an avatar WebP file from disk by its storage key.
 *
 * Returns `null` if the key is malformed or the file is missing.
 * The caller is responsible for producing the HTTP response (including
 * choosing the appropriate `Cache-Control` header for its audience).
 *
 * Used by both the customer-facing serve handler and the admin-facing
 * customer avatar serve handler, to keep file access logic in one place.
 */
export async function readAvatarFile(storageKey: string): Promise<Buffer | null> {
  if (!AVATAR_STORAGE_KEY_REGEX.test(storageKey)) {
    return null;
  }
  const { readFile } = await import('node:fs/promises');
  const path = await import('node:path');
  const basePath = getAvatarBasePath();
  const filePath = path.join(basePath, `${storageKey}.webp`);
  try {
    return await readFile(filePath);
  } catch {
    return null;
  }
}

/**
 * Validate magic bytes of the uploaded file buffer.
 * Returns true if the buffer starts with JPEG, PNG, or WebP magic bytes.
 */
function isAllowedImageFormat(buffer: Uint8Array): boolean {
  if (buffer.length < 12) return false;

  // JPEG: FFD8FF
  if (
    buffer[0] === JPEG_MAGIC[0] &&
    buffer[1] === JPEG_MAGIC[1] &&
    buffer[2] === JPEG_MAGIC[2]
  ) {
    return true;
  }

  // PNG: 89504E47
  if (
    buffer[0] === PNG_MAGIC[0] &&
    buffer[1] === PNG_MAGIC[1] &&
    buffer[2] === PNG_MAGIC[2] &&
    buffer[3] === PNG_MAGIC[3]
  ) {
    return true;
  }

  // WebP: RIFF....WEBP
  if (
    buffer[0] === RIFF_MAGIC[0] &&
    buffer[1] === RIFF_MAGIC[1] &&
    buffer[2] === RIFF_MAGIC[2] &&
    buffer[3] === RIFF_MAGIC[3] &&
    buffer[8] === WEBP_MAGIC[0] &&
    buffer[9] === WEBP_MAGIC[1] &&
    buffer[10] === WEBP_MAGIC[2] &&
    buffer[11] === WEBP_MAGIC[3]
  ) {
    return true;
  }

  return false;
}

// ---------------------------------------------------------------------------
// handleGetProfile
// ---------------------------------------------------------------------------

/**
 * GET /api/customer/profile
 *
 * Returns the full customer profile with mutability metadata for each field.
 */
export async function handleGetProfile(ctx: CustomerContext): Promise<NextResponse> {
  const { customer, db } = ctx;

  // Fetch the full customer row (the context only has a subset)
  // Crivacy stores ZERO raw PII columns post PII-purge migration
  // (20260509000000) — full_name / date_of_birth / nationality /
  // document_* / address_* are NOT selected because they no longer
  // exist on this table. The customer can view their underlying PII
  // by following the Didit deep-link surfaced elsewhere in the UI.
  const rows = await db
    .select({
      id: schema.customers.id,
      email: schema.customers.email,
      displayName: schema.customers.displayName,
      phone: schema.customers.phone,
      kycFieldsLocked: schema.customers.kycFieldsLocked,
      avatarStorageKey: schema.customers.avatarStorageKey,
      kycLevel: schema.customers.kycLevel,
      kycScore: schema.customers.kycScore,
      emailVerifiedAt: schema.customers.emailVerifiedAt,
      onboardingDismissedAt: schema.customers.onboardingDismissedAt,
      createdAt: schema.customers.createdAt,
      updatedAt: schema.customers.updatedAt,
    })
    .from(schema.customers)
    .where(eq(schema.customers.id, customer.id))
    .limit(1);

  const row = rows[0];
  if (row === undefined) {
    return ctx.errorJson('not_found', 'Customer profile not found.', 404);
  }

  const avatarUrl =
    row.avatarStorageKey !== null
      ? `/api/customer/avatar/${row.avatarStorageKey}`
      : null;

  return ctx.json({
    id: row.id,
    email: row.email,
    displayName: row.displayName,
    phone: row.phone,
    // No PII fields — Crivacy holds none. The customer can fetch
    // their underlying KYC data from Didit via the deep-link
    // surfaced on the verification card.
    kycLevel: row.kycLevel,
    kycScore: row.kycScore,
    avatarUrl,
    emailVerifiedAt: row.emailVerifiedAt !== null ? row.emailVerifiedAt.toISOString() : null,
    onboardingDismissedAt: row.onboardingDismissedAt !== null ? row.onboardingDismissedAt.toISOString() : null,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
    mutability: buildMutabilityMap(row.kycFieldsLocked),
  });
}

// ---------------------------------------------------------------------------
// handleUpdateProfile
// ---------------------------------------------------------------------------

/**
 * PATCH /api/customer/profile
 *
 * Update editable profile fields (displayName, phone). Rejects attempts
 * to modify immutable or locked fields.
 */
export async function handleUpdateProfile(ctx: CustomerContext): Promise<NextResponse> {
  const { customer, db, now, request } = ctx;

  // --- 1. Parse and validate body ---
  let body: z.infer<typeof UpdateProfileSchema>;
  try {
    const contentType = request.headers.get('content-type');
    if (contentType === null || !contentType.includes('application/json')) {
      return ctx.errorJson('unsupported_media_type', 'Content-Type must be application/json.', 415);
    }
    const raw = await request.json();
    body = UpdateProfileSchema.parse(raw);
  } catch (err) {
    if (err instanceof z.ZodError) {
      return ctx.errorJson('validation_failed', 'Invalid input.', 400, {
        issues: err.issues.map((i) => ({ path: i.path, message: i.message })),
      });
    }
    return ctx.errorJson('malformed_json', 'Request body is not valid JSON.', 400);
  }

  // Nothing to update
  if (body.displayName === undefined && body.phone === undefined && body.onboardingDismissed === undefined) {
    return ctx.errorJson('validation_failed', 'No fields to update.', 400);
  }

  // --- 2. Check kycFieldsLocked for phone ---
  if (body.phone !== undefined) {
    const lockRows = await db
      .select({ kycFieldsLocked: schema.customers.kycFieldsLocked })
      .from(schema.customers)
      .where(eq(schema.customers.id, customer.id))
      .limit(1);

    const lockRow = lockRows[0];
    if (lockRow !== undefined && lockRow.kycFieldsLocked) {
      return ctx.errorJson(
        'field_locked',
        'Phone number cannot be changed after KYC verification.',
        403,
      );
    }

    // Check phone uniqueness among active (non-deleted) customers
    const phoneConflict = await db
      .select({ id: schema.customers.id })
      .from(schema.customers)
      .where(
        and(
          eq(schema.customers.phone, body.phone),
          ne(schema.customers.id, customer.id),
          isNull(schema.customers.deletedAt),
        ),
      )
      .limit(1);

    if (phoneConflict.length > 0) {
      return ctx.errorJson(
        'conflict',
        'This phone number is already associated with another account.',
        409,
      );
    }
  }

  // --- 3. Prepare update values ---
  const updates: Record<string, unknown> = { updatedAt: now };
  const auditActions: Array<{ action: 'customer.profile_updated' | 'customer.phone_updated'; meta: Record<string, unknown> }> = [];

  if (body.displayName !== undefined) {
    const normalized = normalizeDisplayName(body.displayName);
    if (normalized.length < 2) {
      return ctx.errorJson(
        'validation_failed',
        'Display name must be at least 2 characters after normalization.',
        400,
      );
    }
    updates['displayName'] = normalized;
    auditActions.push({
      action: 'customer.profile_updated',
      meta: { field: 'displayName', newValue: normalized },
    });
  }

  if (body.phone !== undefined) {
    updates['phone'] = body.phone;
    auditActions.push({
      action: 'customer.phone_updated',
      meta: { field: 'phone' },
    });
  }

  if (body.onboardingDismissed === true) {
    updates['onboardingDismissedAt'] = now;
    auditActions.push({
      action: 'customer.profile_updated',
      meta: { field: 'onboardingDismissedAt' },
    });
  }

  // --- 4. Update ---
  await db
    .update(schema.customers)
    .set(updates)
    .where(eq(schema.customers.id, customer.id));

  // --- 5. Audit ---
  const actor = customerActor({
    id: customer.id,
    label: customerLabel(customer),
  });
  const target = uuidTarget({ kind: 'customer', id: customer.id });
  const auditCtx = buildAuditRequestContext({
    ip: ctx.ip,
    userAgent: ctx.userAgent,
    requestId: ctx.requestId,
  });

  for (const entry of auditActions) {
    await writeAudit(db, {
      action: entry.action,
      actor,
      target,
      context: auditCtx,
      meta: entry.meta,
      ts: now,
    });
  }

  return ctx.json({ updated: true });
}

// ---------------------------------------------------------------------------
// handleUploadAvatar
// ---------------------------------------------------------------------------

/**
 * POST /api/customer/avatar
 *
 * Upload a new avatar image. Accepts multipart/form-data with a single
 * `avatar` file field. Validates magic bytes, resizes to 512x512 via
 * sharp, strips EXIF, converts to WebP, and stores on disk.
 */
export async function handleUploadAvatar(ctx: CustomerContext): Promise<NextResponse> {
  const { customer, db, now, request } = ctx;

  // --- 1. Parse multipart form data ---
  let formData: FormData;
  try {
    formData = await request.formData();
  } catch {
    return ctx.errorJson(
      'unsupported_media_type',
      'Request must be multipart/form-data with an avatar file.',
      415,
    );
  }

  const file = formData.get('avatar');
  if (file === null || typeof file === 'string') {
    return ctx.errorJson('validation_failed', 'Missing "avatar" file field.', 400);
  }

  // --- 2. Size check ---
  if (file.size > MAX_AVATAR_BYTES) {
    return ctx.errorJson(
      'payload_too_large',
      `Avatar file must be at most ${String(MAX_AVATAR_BYTES / 1024 / 1024)} MB.`,
      413,
    );
  }

  if (file.size === 0) {
    return ctx.errorJson('validation_failed', 'Avatar file is empty.', 400);
  }

  // --- 3. Read bytes and validate magic bytes ---
  const arrayBuffer = await file.arrayBuffer();
  const buffer = new Uint8Array(arrayBuffer);

  if (!isAllowedImageFormat(buffer)) {
    return ctx.errorJson(
      'validation_failed',
      'Only JPEG, PNG, and WebP images are allowed.',
      400,
    );
  }

  // --- 4. Process with sharp: strip EXIF, resize 512x512, convert to WebP ---
  const sharp = (await import('sharp')).default;
  let processedBuffer: Buffer;
  try {
    processedBuffer = await sharp(Buffer.from(arrayBuffer), SHARP_INPUT_GUARD)
      .rotate() // Auto-orient based on EXIF before stripping
      .resize(512, 512, { fit: 'cover', position: 'centre' })
      .removeAlpha()
      .webp({ quality: 85 })
      .toBuffer();
  } catch {
    return ctx.errorJson(
      'processing_failed',
      'Failed to process the image. Please try a different file.',
      422,
    );
  }

  // --- 5. Store to disk ---
  const { mkdir, writeFile, unlink } = await import('node:fs/promises');
  const path = await import('node:path');

  const basePath = getAvatarBasePath();
  await mkdir(basePath, { recursive: true });

  const newUuid = crypto.randomUUID();
  const filePath = path.join(basePath, `${newUuid}.webp`);
  await writeFile(filePath, processedBuffer);

  // --- 6. Delete old avatar file if exists ---
  const oldRows = await db
    .select({ avatarStorageKey: schema.customers.avatarStorageKey })
    .from(schema.customers)
    .where(eq(schema.customers.id, customer.id))
    .limit(1);

  const oldKey = oldRows[0]?.avatarStorageKey;
  if (oldKey !== null && oldKey !== undefined) {
    const oldPath = path.join(basePath, `${oldKey}.webp`);
    try {
      await unlink(oldPath);
    } catch {
      // Old file may already be deleted — ignore
    }
  }

  // --- 7. Update DB ---
  await db
    .update(schema.customers)
    .set({ avatarStorageKey: newUuid, updatedAt: now })
    .where(eq(schema.customers.id, customer.id));

  // --- 8. Audit ---
  const actor = customerActor({ id: customer.id, label: customerLabel(customer) });
  const target = uuidTarget({ kind: 'customer', id: customer.id });
  const auditCtx = buildAuditRequestContext({
    ip: ctx.ip,
    userAgent: ctx.userAgent,
    requestId: ctx.requestId,
  });

  await writeAudit(db, {
    action: 'customer.avatar_updated',
    actor,
    target,
    context: auditCtx,
    meta: { avatarStorageKey: newUuid },
    ts: now,
  });

  return ctx.json({ avatarUrl: `/api/customer/avatar/${newUuid}` }, 201);
}

// ---------------------------------------------------------------------------
// handleDeleteAvatar
// ---------------------------------------------------------------------------

/**
 * DELETE /api/customer/avatar
 *
 * Remove the customer's avatar image. Deletes the file from disk and
 * clears the avatarStorageKey in the DB.
 */
export async function handleDeleteAvatar(ctx: CustomerContext): Promise<NextResponse> {
  const { customer, db, now } = ctx;

  // --- 1. Get current avatar key ---
  const rows = await db
    .select({ avatarStorageKey: schema.customers.avatarStorageKey })
    .from(schema.customers)
    .where(eq(schema.customers.id, customer.id))
    .limit(1);

  const row = rows[0];
  if (row === undefined || row.avatarStorageKey === null) {
    return ctx.errorJson('not_found', 'No avatar to delete.', 404);
  }

  // --- 2. Delete file ---
  const { unlink } = await import('node:fs/promises');
  const path = await import('node:path');
  const basePath = getAvatarBasePath();
  const filePath = path.join(basePath, `${row.avatarStorageKey}.webp`);

  try {
    await unlink(filePath);
  } catch {
    // File may already be deleted — proceed to clear DB
  }

  // --- 3. Clear DB ---
  await db
    .update(schema.customers)
    .set({ avatarStorageKey: null, updatedAt: now })
    .where(eq(schema.customers.id, customer.id));

  // --- 4. Audit ---
  const actor = customerActor({ id: customer.id, label: customerLabel(customer) });
  const target = uuidTarget({ kind: 'customer', id: customer.id });
  const auditCtx = buildAuditRequestContext({
    ip: ctx.ip,
    userAgent: ctx.userAgent,
    requestId: ctx.requestId,
  });

  await writeAudit(db, {
    action: 'customer.avatar_removed',
    actor,
    target,
    context: auditCtx,
    meta: { removedKey: row.avatarStorageKey },
    ts: now,
  });

  return ctx.noContent();
}

// ---------------------------------------------------------------------------
// handleServeAvatar
// ---------------------------------------------------------------------------

/**
 * GET /api/customer/avatar/[uuid]
 *
 * Serve the avatar image for the given storage key. Returns the WebP
 * file with immutable cache headers. The route is public within the
 * customer auth context — only the authenticated customer's UUID will
 * resolve to a file.
 */
export async function handleServeAvatar(
  ctx: CustomerContext,
  uuid: string,
): Promise<NextResponse> {
  const fileBuffer = await readAvatarFile(uuid);
  if (fileBuffer === null) {
    return ctx.errorJson('not_found', 'Avatar not found.', 404);
  }

  return new NextResponse(fileBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'image/webp',
      // AUD-CUS-CACHE-001 fix: `private` so a CDN between client and
      // origin cannot cache this auth-gated response with a URL-only
      // key. Without this, the first authenticated customer to hit
      // `/api/customer/avatar/<uuid>` would populate the shared
      // cache, and any later unauthenticated request to the same URL
      // (the UUID is unguessable but can leak via logs, ticket
      // attachments, etc.) would bypass the customerRoute auth gate
      // entirely. `private` keeps the browser's per-user cache alive
      // while forbidding shared-cache storage.
      'Cache-Control': 'private, max-age=86400, immutable',
      'Content-Length': String(fileBuffer.length),
      'x-request-id': ctx.requestId,
    },
  });
}
