/**
 * Next.js Edge Middleware — lightweight auth gate + Content-Security-Policy.
 *
 * Two responsibilities, kept here so every response leaving the runtime
 * carries the same CSP without each route handler re-emitting it:
 *
 *   1. Cookie PRESENCE auth gate (not JWT verification — that happens
 *      in the route handlers) so unauthed users don't see flash-of-content
 *      on protected pages.
 *   2. Per-request CSP nonce mint + header injection. Removes the legacy
 *      `'unsafe-inline'` from `script-src` by minting a fresh nonce per
 *      request, writing it on `x-nonce` so Next can stamp it onto its
 *      inline bootstrap scripts (the Next 13.4+ canonical pattern), and
 *      emitting `script-src 'self' 'nonce-XXX' 'strict-dynamic'` so the
 *      browser only executes scripts that carry the nonce or are loaded
 *      by a script that does. Pages MUST be dynamically rendered for
 *      this to work — see the `export const dynamic = 'force-dynamic'`
 *      lines on every route group layout. Static pages cannot read
 *      `headers()` at render time and would land in the response with
 *      no nonce attribute, blocking React hydration.
 *
 * Auth redirect: logged-in users visiting auth pages (login, register,
 * forgot-password, reset-password) are redirected to their home page.
 *
 * Cookie names:
 *   __crivacy_ct       — customer access token
 *   __crivacy_at       — firm dashboard access token
 *   __crivacy_admin_at — admin access token
 */

import { NextResponse, type NextRequest } from 'next/server';

import {
  CUSTOMER_ACCESS_COOKIE,
  DASHBOARD_ACCESS_COOKIE,
  ADMIN_ACCESS_COOKIE,
} from '@/lib/auth/cookie-names';
import { isMaintenanceExempt, isMaintenanceMode } from '@/lib/env/maintenance';
import { sanitizeSameOriginPath } from '@/lib/security/safe-redirect';
import { THEME_INIT_SCRIPT_CSP_HASH } from '@/lib/security/theme-init-script';

const CUSTOMER_COOKIE = CUSTOMER_ACCESS_COOKIE;
const DASHBOARD_COOKIE = DASHBOARD_ACCESS_COOKIE;
const ADMIN_COOKIE = ADMIN_ACCESS_COOKIE;

/**
 * Routes that are always public — no auth check needed.
 * Matched by prefix against the pathname.
 */
const PUBLIC_PREFIXES = [
  '/terms',
  '/privacy',
  '/api/',
  '/health',
  '/_next/',
  '/favicon',
  '/not-found',
  // Public static assets (`public/assets/**`) — firm drop-in kit
  // (`/assets/crivacy/v1/crivacy.js`, `button.css`, `logo.svg`),
  // uploaded avatars, anything a browser fetches as a resource.
  // Without this the customer-cookie fallback would 307 these
  // requests to `/login`, breaking every consumer that links our
  // snippet into their own page.
  '/assets/',
  // OAuth consent / authorize surfaces run their own auth checks and
  // need to preserve ?request=<id> through any login round-trip. The
  // global auth middleware strips query params when building the
  // `from=` redirect, so we opt /oauth/* out entirely — the consent
  // page performs its own 401 → /login bounce with the full URL.
  '/oauth/',
  // Docs are the firm-facing marketing / reference surface. They must
  // be readable without a Crivacy customer session, otherwise new
  // integrators bounce off the login wall before they can read how
  // to integrate.
  '/docs',
  '/status',
  // KYC device handoff landing page. Phone scans the QR generated by
  // the desktop, lands here. The token in the URL IS the auth (256-bit
  // entropy + DB-side SHA256 hash + 10min TTL + one-shot CAS consume
  // + per-session cap of 5). The phone has no Crivacy session cookie
  // by design: desktop generates, phone consumes, no auth carried
  // across devices. Without this bypass the customer-cookie gate
  // would 307 the phone to /login and burn the handoff token in the
  // process.
  '/kyc/handoff/',
  // KYC post-verification UX landing page — Didit redirects the
  // user's browser here after they finish the hosted flow. Phone is
  // unauthenticated (no Crivacy session cookie carried across
  // devices) so the page must render without a customer session. The
  // page itself is a static "verification complete, return to your
  // computer" surface — it makes ZERO state-mutating decisions, does
  // NOT trust the URL query string (`?status=` / `?verificationSessionId=`
  // are client-controllable; an attacker could craft them at will),
  // and does NOT perform a DB lookup based on user input. State
  // propagation back to the desktop runs through the SSE pull-fallback
  // + signed webhook channels — this page exists purely to give the
  // phone a friendly "you're done" screen instead of a 4xx on the
  // webhook endpoint.
  '/kyc/callback',
] as const;

/**
 * Auth pages — if user is already logged in (has customer cookie),
 * redirect to home instead of showing auth forms.
 */
const CUSTOMER_AUTH_PAGES = [
  '/login',
  '/register',
  '/forgot-password',
  '/reset-password',
  '/verify-email',
  '/complete-registration',
] as const;

/**
 * Dashboard (firm) login page — don't require auth.
 */
const DASHBOARD_LOGIN = '/dashboard/login';

/**
 * Dashboard accept-invite page — reached from the welcome email
 * *before* the firm user has any credentials, so it must bypass the
 * dashboard-cookie gate.
 */
const DASHBOARD_ACCEPT_INVITE = '/dashboard/accept-invite';

/**
 * Forgot/reset-password pages — the user is definitionally unable to
 * log in when they're here. Same bypass as login and accept-invite.
 */
const DASHBOARD_FORGOT_PASSWORD = '/dashboard/forgot-password';
const DASHBOARD_RESET_PASSWORD = '/dashboard/reset-password';

/**
 * Admin login page — don't require auth.
 */
const ADMIN_LOGIN = '/admin/login';

function isPublicRoute(pathname: string): boolean {
  for (const prefix of PUBLIC_PREFIXES) {
    if (pathname.startsWith(prefix)) return true;
  }
  return false;
}

function isCustomerAuthPage(pathname: string): boolean {
  for (const page of CUSTOMER_AUTH_PAGES) {
    if (pathname === page || pathname.startsWith(page + '/')) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// CSP nonce + header
// ---------------------------------------------------------------------------

/**
 * 16 random bytes, base64-encoded — 24 chars in URL-safe-ish form. The
 * edge runtime ships `crypto.getRandomValues` and `btoa` as globals so we
 * do not need any node-builtin shim. Each request gets a fresh value so
 * a leaked nonce cannot replay on another response.
 */
function generateNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  let bin = '';
  for (let i = 0; i < bytes.length; i += 1) {
    bin += String.fromCharCode(bytes[i]!);
  }
  return btoa(bin);
}

/**
 * Build the Content-Security-Policy header value for a single request.
 *
 * `script-src` uses `'nonce-${nonce}' 'strict-dynamic'`:
 *   - `'nonce-XXX'` permits inline scripts that carry the matching
 *     attribute. Next.js 13.4+ stamps this nonce onto every inline
 *     bootstrap script automatically when it sees `x-nonce` on the
 *     incoming request headers — that's why the middleware writes it
 *     onto `requestHeaders` before the response is built.
 *   - `'strict-dynamic'` instructs the browser to trust scripts loaded
 *     by an already-trusted (nonced) script, which lets Next's chunk
 *     loaders fan out the rest of the bundle without each chunk
 *     individually carrying a nonce. In strict-dynamic mode browsers
 *     ignore the host-source allowlist (`'self'`, `https://...`); old
 *     non-strict-dynamic browsers fall back to those allowlists, so
 *     keeping `'self'` in the directive preserves graceful degradation.
 *   - `'unsafe-inline'` is gone. Any inline script that does not carry
 *     the nonce — e.g. a hypothetical XSS payload smuggled through a
 *     missed sanitiser — is blocked by the browser before it executes.
 *     This is the actual hardening the rest of this commit chases.
 *
 * `style-src` keeps `'unsafe-inline'`. Tailwind utility classes and
 * next/font both emit inline style attributes on every component;
 * removing the directive would break the whole UI. Style XSS is a far
 * narrower vector than script XSS — the residual risk is acceptable
 * relative to the rendering cost of a hash-based or nonce-based style
 * directive in this codebase.
 *
 * Other directives mirror the legacy `next.config.mjs` baseline: same
 * `frame-ancestors`, `frame-src` (Cloudflare Turnstile), `connect-src`
 * shape (HMR websockets in dev, Turnstile in prod). The CSP used to
 * live in `next.config.mjs::headers()` and is being moved here so the
 * per-request nonce can be substituted in.
 */
function buildCsp(nonce: string, isDev: boolean, originSelf: string | null = null): string {
  // In dev on non-localhost HTTP origins (LAN IP for phone testing), Chrome
  // sometimes rejects `'self'` in `form-action` even when the action target
  // is same-origin — the keyword is interpreted strictly against the
  // browser's "potentially trustworthy" judgement, and a plain HTTP LAN IP
  // misses that bar. Including the explicit origin as a second source
  // bypasses the heuristic without weakening the policy. Prod (HTTPS) is
  // unaffected — `'self'` resolves cleanly there and the explicit origin
  // just duplicates it.
  const dynamicSelf = originSelf !== null ? ` ${originSelf}` : '';
  const scriptSrc = [
    "script-src",
    "'self'",
    `'nonce-${nonce}'`,
    "'strict-dynamic'",
    // Pre-paint theme init script in `app/layout.tsx`. Next 15.5
    // `runtime: 'nodejs'` middleware doesn't propagate
    // `request.headers.set('x-nonce', ...)` into route-handler
    // `headers()`, so the layout would render
    // `<script nonce={undefined}>` and CSP would block it.
    // Hash-based whitelist sidesteps that propagation gap — script
    // content is static (`THEME_INIT_SCRIPT` constant), hash
    // computed once at process boot. Keeps the rest of the script
    // graph nonce-gated. See `lib/security/theme-init-script.ts`.
    THEME_INIT_SCRIPT_CSP_HASH,
    // Dev-only: react-refresh evaluates module source with `eval()` on
    // every HMR tick. No effect on production, where Next emits static
    // chunks. Strict-dynamic does not include eval — it must be
    // listed explicitly.
    ...(isDev ? ["'unsafe-eval'"] : []),
    // Cloudflare Turnstile script. `strict-dynamic` makes most browsers
    // ignore this host source, but legacy browsers (CSP2 only) still
    // honour it as a fallback before they reach `strict-dynamic`.
    'https://challenges.cloudflare.com',
  ].join(' ');

  return [
    "default-src 'self'",
    "base-uri 'self'",
    scriptSrc,
    // Style: see comment above.
    "style-src 'self' 'unsafe-inline'",
    // Images: self + data:/blob: for sharp-generated avatars and the
    // QR-code component (TOTP enrollment uses data-URL PNGs).
    "img-src 'self' data: blob:",
    // Fonts: self + next/font's data URIs.
    "font-src 'self' data:",
    // Fetch: same-origin + Turnstile token verify. Dev adds the HMR
    // websocket origin — the Next overlay and react-refresh stream
    // errors/updates through ws://host:port.
    isDev
      ? `connect-src 'self'${dynamicSelf} https://challenges.cloudflare.com ws: wss:`
      : "connect-src 'self' https://challenges.cloudflare.com",
    // Frames: Cloudflare Turnstile is the only third party we embed.
    "frame-src https://challenges.cloudflare.com",
    "frame-ancestors 'none'",
    `form-action 'self'${dynamicSelf}`,
    "object-src 'none'",
    "media-src 'self'",
    "manifest-src 'self'",
    "worker-src 'self' blob:",
    ...(isDev || process.env['CRIVACY_AUDIT_LOCAL_HTTP'] === 'true' ? [] : ['upgrade-insecure-requests']),
  ].join('; ');
}

/**
 * Forward the request to Next with the nonce on `x-nonce`, then stamp
 * the matching CSP header onto the response. Preserves any existing
 * headers the caller set (e.g. `Cache-Control: no-store` for auth
 * pages).
 */
function withCsp(
  request: NextRequest,
  buildResponse: (requestHeaders: Headers) => NextResponse,
): NextResponse {
  const nonce = generateNonce();
  const isDev = process.env.NODE_ENV !== 'production';
  // Pull the request's actual origin from forwarded headers (dev runs
  // behind no proxy, so `host` is the address bar host). Dev only —
  // production omits it so the policy stays minimal and explicit.
  let originSelf: string | null = null;
  if (isDev) {
    const host = request.headers.get('host');
    if (host !== null && host.length > 0) {
      const proto = request.headers.get('x-forwarded-proto') ?? 'http';
      originSelf = `${proto}://${host}`;
    }
  }
  const csp = buildCsp(nonce, isDev, originSelf);

  // Mutate the request headers Next forwards to the route handlers.
  // `next/headers::headers()` reads from this map at render time, so
  // server components / pages can pull the nonce via
  // `headers().get('x-nonce')` and pass it to a `<Script nonce={...}>`
  // tag if they emit one explicitly.
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-nonce', nonce);
  // Next 13.4+ also inspects the request-side CSP header to know which
  // nonce to bake into its built-in inline bootstrap scripts. Setting
  // it here is the documented way to opt into nonced bootstrap.
  requestHeaders.set('Content-Security-Policy', csp);

  const res = buildResponse(requestHeaders);
  res.headers.set('Content-Security-Policy', csp);
  return res;
}

/**
 * Pass-through response with `Cache-Control: no-store` so browsers never
 * serve auth pages from bfcache. Without this, returning from an OAuth
 * provider (Google, wallet) briefly paints the cached login page before
 * the callback redirect completes.
 *
 * Now also injects the per-request nonce + CSP — see {@link withCsp}.
 */
function noStoreNext(request: NextRequest): NextResponse {
  return withCsp(request, (requestHeaders) => {
    const res = NextResponse.next({ request: { headers: requestHeaders } });
    res.headers.set('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
    res.headers.set('Pragma', 'no-cache');
    return res;
  });
}

/**
 * Pass-through response that carries the per-request nonce + CSP. Use
 * this anywhere the previous code called `NextResponse.next()` directly.
 */
function passThrough(request: NextRequest): NextResponse {
  return withCsp(request, (requestHeaders) =>
    NextResponse.next({ request: { headers: requestHeaders } }),
  );
}

/**
 * Build a 3xx redirect response that ALSO carries a Content-Security-
 * Policy header. Browsers follow the Location header before evaluating
 * the body, so a missing CSP on a redirect response is rarely
 * exploitable on its own — but defense-in-depth is the whole point of
 * this commit. A response without CSP would let an attacker who finds
 * a way to inject HTML into the redirect body (header smuggling, edge
 * proxy bug, future error-page rewriter) ship inline scripts. The
 * redirect path doesn't need the request-header `x-nonce` forward
 * (Next never renders the body — there is no inline script to nonce),
 * so we mint a nonce purely for the response-side header to keep CSP
 * shape uniform across every middleware exit.
 */
function redirectWithCsp(url: URL): NextResponse {
  const nonce = generateNonce();
  const isDev = process.env.NODE_ENV !== 'production';
  const csp = buildCsp(nonce, isDev, isDev ? url.origin : null);
  const res = NextResponse.redirect(url);
  res.headers.set('Content-Security-Policy', csp);
  return res;
}

/**
 * 503 body rendered for every non-exempt request when
 * `CRIVACY_MAINTENANCE_MODE` is on. Minimal payload — we want the
 * response to leave the server as fast as possible during an
 * incident. `Retry-After: 60` is a hint, not a contract — the next
 * probe will still be 503 until the env flag is unset and the
 * process restarted.
 */
const MAINTENANCE_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Maintenance</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  body{font-family:system-ui,-apple-system,sans-serif;background:#0a0a0b;color:#f5f5f7;
       display:grid;place-items:center;min-height:100vh;margin:0;padding:24px;}
  main{max-width:520px;text-align:center;}
  h1{color:#10b981;font-size:24px;margin:0 0 16px;}
  p{color:#a1a1aa;line-height:1.6;margin:0 0 12px;}
  a{color:#10b981;}
</style></head><body><main>
<h1>Crivacy is undergoing maintenance</h1>
<p>We are briefly paused while our team investigates. Existing sessions will need to sign in again once service resumes.</p>
<p>Live updates: <a href="/status">status.crivacy.io</a></p>
</main></body></html>`;

function maintenanceResponse(request: NextRequest): NextResponse {
  const accept = request.headers.get('accept') ?? '';
  const wantsJson = accept.includes('application/json') || request.nextUrl.pathname.startsWith('/api/');
  // Mint a nonce + CSP for the 503 response too. The maintenance HTML
  // body only carries a single inline `<style>` tag (covered by
  // `style-src 'unsafe-inline'`) and zero inline scripts, so the CSP
  // is functionally invariant — but keeping the header on every exit
  // path means an attacker who finds a way to influence the
  // maintenance body (config injection, edge rewriter, future error
  // hook) cannot ship inline scripts past the browser.
  const nonce = generateNonce();
  const isDev = process.env.NODE_ENV !== 'production';
  let originSelf: string | null = null;
  if (isDev) {
    const host = request.headers.get('host');
    if (host !== null && host.length > 0) {
      const proto = request.headers.get('x-forwarded-proto') ?? 'http';
      originSelf = `${proto}://${host}`;
    }
  }
  const csp = buildCsp(nonce, isDev, originSelf);
  if (wantsJson) {
    return new NextResponse(
      JSON.stringify({
        error: {
          code: 'maintenance',
          message: 'Crivacy is undergoing maintenance. Please retry shortly.',
        },
      }),
      {
        status: 503,
        headers: {
          'Content-Type': 'application/json',
          'Cache-Control': 'no-store',
          'Retry-After': '60',
          'Content-Security-Policy': csp,
        },
      },
    );
  }
  return new NextResponse(MAINTENANCE_HTML, {
    status: 503,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'Retry-After': '60',
      'Content-Security-Policy': csp,
    },
  });
}


// ---------------------------------------------------------------------------
// Soft-launch auth kill switch.
//
// When AUTH_DISABLED=true env flag is set, every auth-creating endpoint
// short-circuits to HTTP 503 before any business logic runs. Visitors can
// still LOAD login/register/forgot-password pages so the product shell is
// visible, but every submit goes nowhere. Logout + session-probe paths
// stay open so any pre-existing sessions can close cleanly.
// ---------------------------------------------------------------------------
const AUTH_CREATING_PREFIXES = [
  '/api/customer/auth/login',
  '/api/customer/auth/register',
  '/api/customer/auth/forgot-password',
  '/api/customer/auth/reset-password',
  '/api/customer/auth/verify-email',
  '/api/customer/auth/verify-reset-code',
  '/api/customer/auth/resend-verification',
  '/api/customer/auth/google',
  '/api/customer/auth/wallet',
  '/api/internal/auth/login',
  '/api/internal/auth/forgot-password',
  '/api/internal/auth/reset-password',
  '/api/internal/auth/verify-reset-code',
  '/api/internal/auth/invite/accept',
  '/api/internal/auth/totp',
  '/api/internal/admin/auth/login',
  '/api/internal/admin/auth/totp',
];

function isAuthCreatingPath(pathname: string): boolean {
  for (const prefix of AUTH_CREATING_PREFIXES) {
    if (pathname.startsWith(prefix)) return true;
  }
  return false;
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  if (process.env['AUTH_DISABLED'] === 'true' && isAuthCreatingPath(pathname)) {
    return NextResponse.json(
      {
        error: 'auth_disabled',
        message: 'Sign-up and sign-in are temporarily disabled. Visit https://crivacy.io/tech for updates.',
      },
      { status: 503 },
    );
  }


  // Kill-switch: highest-priority gate. When the env flag is set,
  // everything except the small exempt list (admin incident response,
  // health probe, public status page, static assets) returns 503
  // before any cookie / JWT check runs. Cookie gating below is
  // pointless under maintenance — the backend is intentionally not
  // serving authenticated traffic. See
  // `docs/runbooks/maintenance-mode.md` for activation procedure.
  if (isMaintenanceMode() && !isMaintenanceExempt(pathname)) {
    return maintenanceResponse(request);
  }

  // Public routes — always pass through (with CSP nonce + headers).
  if (isPublicRoute(pathname)) {
    return passThrough(request);
  }

  // Dashboard login page — pass through (but redirect if already logged in)
  if (pathname === DASHBOARD_LOGIN) {
    if (request.cookies.has(DASHBOARD_COOKIE)) {
      const url = request.nextUrl.clone();
      url.pathname = '/dashboard';
      url.search = '';
      return redirectWithCsp(url);
    }
    return noStoreNext(request);
  }

  // Dashboard accept-invite — always pass through. The invitee is by
  // definition not logged in yet; redirecting logged-in users away
  // would also be wrong (they may have a different account open in
  // another tab and be accepting a fresh invite).
  if (pathname === DASHBOARD_ACCEPT_INVITE) {
    return noStoreNext(request);
  }

  // Forgot/reset-password — always pass through for the same reason:
  // the user got here because they can't sign in, so the dashboard
  // cookie gate would trap them in a redirect loop back to login.
  if (pathname === DASHBOARD_FORGOT_PASSWORD || pathname === DASHBOARD_RESET_PASSWORD) {
    return noStoreNext(request);
  }

  // Admin login page — pass through (but redirect if already logged in)
  if (pathname === ADMIN_LOGIN) {
    if (request.cookies.has(ADMIN_COOKIE)) {
      const url = request.nextUrl.clone();
      url.pathname = '/admin';
      url.search = '';
      return redirectWithCsp(url);
    }
    return noStoreNext(request);
  }

  // Customer auth pages — redirect to home if already logged in.
  // When `?from=` is present we honour it (same-origin only) so
  // an authed user who hit /login mid-OAuth (the consent page
  // bounced them here) lands back on the consent surface instead
  // of the dashboard root.
  if (isCustomerAuthPage(pathname)) {
    if (request.cookies.has(CUSTOMER_COOKIE)) {
      const from = request.nextUrl.searchParams.get('from');
      // Centralised same-origin guard — handles backslash, control
      // char, protocol-relative, unicode host edge cases (AUD-X-REDIRECT-001).
      const safeFrom = sanitizeSameOriginPath(from, request.nextUrl.origin);
      const url = request.nextUrl.clone();
      url.pathname = safeFrom;
      // `safeFrom` may carry its own query string (e.g.
      // `/oauth/consent?request=…`). Parse + re-apply so the
      // destination URL survives the redirect intact.
      const questionIdx = safeFrom.indexOf('?');
      if (questionIdx >= 0) {
        url.pathname = safeFrom.slice(0, questionIdx);
        url.search = safeFrom.slice(questionIdx);
      } else {
        url.search = '';
      }
      return redirectWithCsp(url);
    }
    return noStoreNext(request);
  }

  // Admin routes — require admin cookie
  if (pathname.startsWith('/admin')) {
    const hasToken = request.cookies.has(ADMIN_COOKIE);
    if (!hasToken) {
      const url = request.nextUrl.clone();
      url.pathname = ADMIN_LOGIN;
      url.searchParams.set('from', pathname);
      return redirectWithCsp(url);
    }
    return passThrough(request);
  }

  // Dashboard routes — require dashboard cookie
  if (pathname.startsWith('/dashboard')) {
    const hasToken = request.cookies.has(DASHBOARD_COOKIE);
    if (!hasToken) {
      const url = request.nextUrl.clone();
      url.pathname = DASHBOARD_LOGIN;
      url.searchParams.set('from', pathname);
      return redirectWithCsp(url);
    }
    return passThrough(request);
  }

  // Customer routes (everything else: /, /kyc, /settings, /tickets, /credential, etc.)
  const hasToken = request.cookies.has(CUSTOMER_COOKIE);
  if (!hasToken) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    url.searchParams.set('from', pathname);
    return redirectWithCsp(url);
  }

  return passThrough(request);
}

/**
 * Middleware runtime — Node.js, NOT the Edge default.
 *
 * Why: Cat 37b's `CRIVACY_MAINTENANCE_MODE` kill-switch reads
 * `process.env` once per process via `isMaintenanceMode()`. On the
 * Edge runtime, Next.js 15 inlines `process.env.<NAME>` references
 * at build time — flipping the env var at deploy time without a
 * full rebuild does NOT reach the middleware. The kill-switch's
 * documented "redeploy ~30s" tradeoff was actually "rebuild +
 * redeploy", which is operationally too slow for a breach response
 * surface called a "kill-switch".
 *
 * Browser smoke test on 2026-04-25 confirmed the gap: with
 * `CRIVACY_MAINTENANCE_MODE=1` set and `pnpm dev` restarted,
 * `/api/v1/health` (Node runtime) returned `maintenance: true` but
 * `/login` (going through the middleware) returned 200 — the
 * middleware never read the new env value because the Edge bundle
 * had been built before the env change.
 *
 * Switching the middleware to the Node.js runtime closes that gap:
 * `process.env` is now read live at request time. The cost is
 * marginal: every request already pays a DB round-trip in the
 * route handlers (auth lookups, RLS-scoped tx wrappers), so the
 * Edge runtime's microsecond-tier startup advantage is dwarfed by
 * the work that follows. Latency budget per request stays well
 * within the existing Cat 36 SLO.
 *
 * Other Cat 37b assertions (`runtime: 'nodejs'` is the canonical
 * Next.js way to opt out of Edge — documented at
 * https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime).
 */
export const runtime = 'nodejs';

export const config = {
  /**
   * Match everything except static files and _next internals.
   * The actual public/auth checks are done in the function above
   * to keep the matcher simple.
   */
  matcher: [
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico|woff|woff2|ttf|eot)$).*)',
  ],
};
