#!/usr/bin/env bash
# Update the Cloudflare IP allowlist for nginx.
#
# Downloads current Cloudflare IP ranges and writes them to the nginx
# snippet file. Run periodically via cron:
#   0 3 * * 1 /opt/crivacy/scripts/update-cloudflare-ips.sh
#
# After updating, run: nginx -t && systemctl reload nginx

set -euo pipefail

CONF_FILE="/etc/nginx/snippets/cloudflare-ips.conf"
TEMP_FILE=$(mktemp)

trap 'rm -f "$TEMP_FILE"' EXIT

{
  echo "# Cloudflare IP ranges for origin firewall."
  echo "#"
  echo "# Auto-generated by update-cloudflare-ips.sh"
  echo "# Last updated: $(date -u +%Y-%m-%d)"
  echo ""
  echo "# IPv4"
  curl -sf https://www.cloudflare.com/ips-v4 | while IFS= read -r ip; do
    [ -n "$ip" ] && echo "allow $ip;"
  done
  echo ""
  echo "# IPv6"
  curl -sf https://www.cloudflare.com/ips-v6 | while IFS= read -r ip; do
    [ -n "$ip" ] && echo "allow $ip;"
  done
} > "$TEMP_FILE"

# Verify the file has content (at least 10 lines)
LINE_COUNT=$(wc -l < "$TEMP_FILE")
if [ "$LINE_COUNT" -lt 10 ]; then
  echo "ERROR: Generated file has only $LINE_COUNT lines, aborting" >&2
  exit 1
fi

# Atomic replace
mv "$TEMP_FILE" "$CONF_FILE"
echo "Updated $CONF_FILE ($LINE_COUNT lines)"
echo "Run: nginx -t && systemctl reload nginx"
