/**
 * Audit log writer — synchronous, single-row or batch INSERT.
 *
 * The writer is intentionally **synchronous** (i.e. the caller awaits
 * the DB round-trip): the cost of a single-row INSERT into an indexed
 * append-only table is well under 1 ms on a warm connection, and the
 * compliance contract requires zero loss. Queueing the write into an
 * in-memory buffer would leak events on crash.
 *
 * For callers that already hold a transaction (e.g. "create API key
 * AND write audit row atomically") both `writeAudit` and
 * `writeAuditBatch` accept a `tx` parameter that substitutes for the
 * top-level `CrivacyDatabase` and participates in the caller's
 * transaction.
 *
 * The writer validates the input shape and rejects anything that
 * would break the compliance export:
 *
 *   * `action` must be a member of `AUDIT_ACTIONS`
 *   * `actor` must be a constructed `AuditActor`
 *   * `target` must be a constructed `AuditTarget`
 *   * `context` must be a constructed `AuditRequestContext`
 *   * `meta` must serialize to at most `MAX_META_BYTES` of JSON
 *
 * The returned row is the fully-hydrated persisted shape — callers
 * that want the autogenerated `id` and `ts` pass them straight into
 * their response body or into downstream side effects.
 */

import type { CrivacyDatabase } from '@/lib/db/client';
import { auditLog } from '@/lib/db/schema';

import type { AuditAction } from './actions';
import { isAuditAction } from './actions';
import type { AuditActor } from './actors';
import { actorToRow } from './actors';
import type { AuditRequestContext } from './context';
import { EMPTY_CONTEXT } from './context';
import { AuditError } from './errors';
import type { AuditTarget, AuditTargetKind } from './targets';
import { targetToRow } from './targets';

/** Hard cap on the JSON size of the `meta` payload. 64 KiB. */
export const MAX_META_BYTES = 64 * 1024;

/** Hard cap on the number of rows per `writeAuditBatch` call. */
export const MAX_BATCH_SIZE = 500;

/**
 * Input accepted by `writeAudit`. `meta` defaults to an empty object.
 * `context` defaults to the empty context when omitted — use
 * `systemActor(...)` + omitted context for system events.
 */
export interface WriteAuditInput {
  readonly action: AuditAction;
  readonly actor: AuditActor;
  readonly target: AuditTarget;
  readonly context?: AuditRequestContext;
  readonly meta?: Readonly<Record<string, unknown>>;
  /** Optional timestamp override. Defaults to `now()`. Tests use this. */
  readonly ts?: Date;
  /**
   * Outbox event id — set by the security-events subscriber to the
   * UUID of the outbox row driving this write. The audit table has a
   * partial unique index on this column so a retry from the worker's
   * at-least-once delivery hits the index instead of producing a
   * duplicate row. Inline writers omit this field.
   */
  readonly eventId?: string;
}

/** Persisted row shape returned by the writer. Mirrors `audit_log.$inferSelect`. */
export interface PersistedAuditRow {
  readonly id: number;
  readonly actorKind: 'firm_user' | 'admin_user' | 'api_key' | 'system' | 'customer';
  readonly actorId: string | null;
  readonly actorLabel: string;
  readonly firmId: string | null;
  readonly action: AuditAction;
  readonly targetKind: AuditTargetKind | null;
  readonly targetId: string | null;
  readonly targetRef: string | null;
  readonly ip: string | null;
  readonly userAgent: string | null;
  readonly requestId: string | null;
  readonly meta: Readonly<Record<string, unknown>>;
  readonly ts: Date;
}

/**
 * Minimal transaction shape accepted by the writer. Compatible with
 * both the top-level `CrivacyDatabase` and a Drizzle `tx` value
 * inside `db.transaction(...)`.
 */
export type AuditDatabase = Pick<CrivacyDatabase, 'insert'>;

// ---------------- Public surface ----------------

/**
 * Write a single audit row. Throws `AuditError` with a specific code
 * on validation / driver failure; callers should translate it to a
 * 500 response at the API boundary.
 */
export async function writeAudit(
  db: AuditDatabase,
  input: WriteAuditInput,
): Promise<PersistedAuditRow> {
  const row = buildInsertRow(input);
  try {
    const returned = await db.insert(auditLog).values(row).returning();
    const persisted = returned[0];
    if (persisted === undefined) {
      throw new AuditError('write_failed', 'audit insert returned no row');
    }
    return hydrateRow(persisted);
  } catch (cause) {
    if (cause instanceof AuditError) {
      throw cause;
    }
    throw AuditError.wrap('write_failed', 'audit insert failed', cause, {
      action: input.action,
    });
  }
}

/**
 * Write multiple audit rows in a single `INSERT ... VALUES (...)`
 * statement. All rows share the atomicity of whatever transaction
 * the caller is already in (or the implicit single-statement
 * transaction if `db` is the top-level pool).
 *
 * Rejects empty arrays and arrays longer than `MAX_BATCH_SIZE`.
 */
export async function writeAuditBatch(
  db: AuditDatabase,
  inputs: readonly WriteAuditInput[],
): Promise<readonly PersistedAuditRow[]> {
  if (inputs.length === 0) {
    throw new AuditError('batch_empty', 'writeAuditBatch requires at least one row');
  }
  if (inputs.length > MAX_BATCH_SIZE) {
    throw new AuditError(
      'batch_too_large',
      `writeAuditBatch accepts at most ${String(MAX_BATCH_SIZE)} rows`,
      { context: { received: inputs.length } },
    );
  }
  const rows = inputs.map((input) => buildInsertRow(input));
  try {
    const returned = await db.insert(auditLog).values(rows).returning();
    if (returned.length !== rows.length) {
      throw new AuditError('write_failed', 'audit batch insert row count mismatch', {
        context: { expected: rows.length, actual: returned.length },
      });
    }
    return returned.map((r) => hydrateRow(r));
  } catch (cause) {
    if (cause instanceof AuditError) {
      throw cause;
    }
    throw AuditError.wrap('write_failed', 'audit batch insert failed', cause, {
      batchSize: inputs.length,
    });
  }
}

// ---------------- Row construction ----------------

/**
 * Internal insert-row builder. Runs all input validation, freezes
 * the meta payload, and clamps the timestamp. Exported for the
 * chain module so exports can be re-computed from raw inputs without
 * hitting the DB.
 */
export function buildInsertRow(input: WriteAuditInput): InsertAuditRow {
  if (!isAuditAction(input.action)) {
    throw new AuditError('invalid_action', 'action is not a member of AUDIT_ACTIONS', {
      context: { received: input.action },
    });
  }
  const actorRow = actorToRow(input.actor);
  const targetRow = targetToRow(input.target);
  const context = input.context ?? EMPTY_CONTEXT;
  const meta = normalizeMeta(input.meta);
  const ts = normalizeTs(input.ts);

  // If the actor carries a firm id (firm_user, api_key), that wins.
  // If the target carries a firm kind, we use its id only when the
  // actor is system (the "system.firm.backfilled" case).
  const firmId =
    actorRow.firmId ??
    (targetRow.targetKind === 'firm' && targetRow.targetId !== null ? targetRow.targetId : null);

  return {
    actorKind: actorRow.actorKind,
    actorId: actorRow.actorId,
    actorLabel: actorRow.actorLabel,
    firmId,
    action: input.action,
    targetKind: targetRow.targetKind,
    targetId: targetRow.targetId,
    targetRef: targetRow.targetRef,
    ip: context.ip,
    userAgent: context.userAgent,
    requestId: context.requestId,
    meta,
    ts,
    eventId: input.eventId ?? null,
  };
}

/** Shape accepted by `db.insert(auditLog).values(...)`. */
export interface InsertAuditRow {
  readonly actorKind: 'firm_user' | 'admin_user' | 'api_key' | 'system' | 'customer';
  readonly actorId: string | null;
  readonly actorLabel: string;
  readonly firmId: string | null;
  readonly action: AuditAction;
  readonly targetKind: AuditTargetKind | null;
  readonly targetId: string | null;
  readonly targetRef: string | null;
  readonly ip: string | null;
  readonly userAgent: string | null;
  readonly requestId: string | null;
  readonly meta: Readonly<Record<string, unknown>>;
  readonly ts: Date;
  readonly eventId: string | null;
}

/**
 * Sprint 7 Phase J — generic binary-payload guard.
 *
 * `JSON.stringify` silently coerces `Buffer`, `Uint8Array`, `ArrayBuffer`,
 * and `DataView` into `{}` (or, for typed arrays, into a numeric-keyed
 * object that round-trips losslessly only by accident). Audit consumers
 * read the JSONB blob expecting compact, queryable structured data; a
 * 4MB disclosure-blob value silently turning into `{}` is a fidelity
 * loss that's hard to debug and produces an audit trail that can't be
 * used to reconstruct what actually happened.
 *
 * Reject these types up front. Callers that genuinely need to record
 * binary should base64-encode it and store the encoded string, with a
 * length / content-hash field alongside, so the audit row stays
 * structured and grep-able. The rejection covers nested values too
 * (a Buffer two levels deep would be just as silently destroyed).
 *
 * Returns the offending property path (dotted, e.g. `disclosure.blob`)
 * when a binary value is found; null otherwise.
 */
function findBinaryViolation(value: unknown, path: string, seen: WeakSet<object>): string | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== 'object') return null;
  if (Buffer.isBuffer(value)) return path;
  if (value instanceof Uint8Array) return path;
  if (value instanceof ArrayBuffer) return path;
  if (value instanceof DataView) return path;
  // Cycle guard — circular references are caught later by JSON.stringify
  // (which throws TypeError); the walker bails out so it doesn't recurse
  // forever before we even reach that throw.
  if (seen.has(value)) return null;
  seen.add(value);
  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i += 1) {
      const nested = findBinaryViolation(value[i], `${path}[${String(i)}]`, seen);
      if (nested !== null) return nested;
    }
    return null;
  }
  // Plain object — walk own enumerable string-keyed entries.
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    const childPath = path === '' ? key : `${path}.${key}`;
    const nested = findBinaryViolation(child, childPath, seen);
    if (nested !== null) return nested;
  }
  return null;
}

function normalizeMeta(meta: WriteAuditInput['meta']): Readonly<Record<string, unknown>> {
  if (meta === undefined) {
    return EMPTY_META;
  }
  if (typeof meta !== 'object' || meta === null || Array.isArray(meta)) {
    throw new AuditError('invalid_meta', 'meta must be a plain object');
  }
  const binaryPath = findBinaryViolation(meta, '', new WeakSet());
  if (binaryPath !== null) {
    throw new AuditError(
      'invalid_meta',
      `meta contains a binary value at \`${binaryPath}\`. Audit JSONB cannot carry Buffer/Uint8Array/ArrayBuffer/DataView fidelity-preservingly; base64-encode the bytes (with a length/content-hash sibling) before recording.`,
    );
  }
  let serialized: string;
  try {
    serialized = JSON.stringify(meta);
  } catch (cause) {
    throw AuditError.wrap('invalid_meta', 'meta is not JSON-serializable', cause);
  }
  const byteLength = Buffer.byteLength(serialized, 'utf8');
  if (byteLength > MAX_META_BYTES) {
    throw new AuditError('meta_too_large', `meta JSON exceeds ${String(MAX_META_BYTES)} bytes`, {
      context: { byteLength },
    });
  }
  return Object.freeze({ ...meta });
}

const EMPTY_META: Readonly<Record<string, unknown>> = Object.freeze({});

function normalizeTs(ts: Date | undefined): Date {
  if (ts === undefined) {
    return new Date();
  }
  if (!(ts instanceof Date) || Number.isNaN(ts.getTime())) {
    throw new AuditError('invalid_context', 'ts must be a valid Date');
  }
  return ts;
}

// ---------------- Row hydration ----------------

/**
 * Convert a raw returning-row into the strongly-typed
 * `PersistedAuditRow`. Drizzle hands us back an object that matches
 * `$inferSelect`, but the `action` field is typed as `string`; we
 * narrow it to `AuditAction` here after a runtime check.
 */
function hydrateRow(row: unknown): PersistedAuditRow {
  if (typeof row !== 'object' || row === null) {
    throw new AuditError('write_failed', 'driver returned a non-object row');
  }
  const raw = row as Record<string, unknown>;
  const action = raw['action'];
  if (!isAuditAction(action)) {
    throw new AuditError('write_failed', 'persisted row has unknown action', {
      context: { action },
    });
  }
  return {
    id: requireNumber(raw['id'], 'id'),
    actorKind: requireActorKind(raw['actorKind']),
    actorId: nullableString(raw['actorId']),
    actorLabel: requireString(raw['actorLabel'], 'actorLabel'),
    firmId: nullableString(raw['firmId']),
    action,
    targetKind: requireTargetKind(raw['targetKind']),
    targetId: nullableString(raw['targetId']),
    targetRef: nullableString(raw['targetRef']),
    ip: nullableString(raw['ip']),
    userAgent: nullableString(raw['userAgent']),
    requestId: nullableString(raw['requestId']),
    meta: requireObject(raw['meta']),
    ts: requireDate(raw['ts']),
  };
}

const ALLOWED_TARGET_KINDS: readonly AuditTargetKind[] = [
  'firm',
  'firm_user',
  'admin_user',
  'api_key',
  'webhook_endpoint',
  'webhook_delivery',
  'kyc_session',
  'credential',
  'incident',
  'status_component',
  'customer',
  'ticket',
  'role',
  'permission',
  // OAuth client lifecycle targets — added with the OAuth 2.0
  // surface; the allow-list here drifted behind the `AuditTargetKind`
  // union in `targets.ts`, so every oauth_client audit write was
  // failing hydration with "persisted row targetKind is unknown".
  'oauth_client',
  'oauth_consent',
];

function requireTargetKind(value: unknown): AuditTargetKind | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (typeof value !== 'string') {
    throw new AuditError('write_failed', 'persisted row targetKind is not a string or null');
  }
  if (!(ALLOWED_TARGET_KINDS as readonly string[]).includes(value)) {
    throw new AuditError('write_failed', 'persisted row targetKind is unknown', {
      context: { received: value },
    });
  }
  return value as AuditTargetKind;
}

function requireNumber(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new AuditError('write_failed', `persisted row ${field} is not a number`);
  }
  return value;
}

function requireString(value: unknown, field: string): string {
  if (typeof value !== 'string') {
    throw new AuditError('write_failed', `persisted row ${field} is not a string`);
  }
  return value;
}

function nullableString(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (typeof value !== 'string') {
    throw new AuditError('write_failed', 'persisted row field is not a nullable string');
  }
  return value;
}

function requireActorKind(value: unknown): 'firm_user' | 'admin_user' | 'api_key' | 'system' | 'customer' {
  if (
    value === 'firm_user' ||
    value === 'admin_user' ||
    value === 'api_key' ||
    value === 'system' ||
    value === 'customer'
  ) {
    return value;
  }
  throw new AuditError('write_failed', 'persisted row actorKind is unknown', {
    context: { received: value },
  });
}

function requireObject(value: unknown): Readonly<Record<string, unknown>> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new AuditError('write_failed', 'persisted row meta is not a plain object');
  }
  return value as Readonly<Record<string, unknown>>;
}

function requireDate(value: unknown): Date {
  if (value instanceof Date) {
    return value;
  }
  if (typeof value === 'string' || typeof value === 'number') {
    const parsed = new Date(value);
    if (!Number.isNaN(parsed.getTime())) {
      return parsed;
    }
  }
  throw new AuditError('write_failed', 'persisted row ts is not a Date');
}
